/turtlesim:
  ros__parameters:
    background_b: 0
    background_g: 0
    background_r: 255
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
/move_turtle:
  ros__parameters:
    linear_velocity: 2.0
    angular_velocity: 1.0