#!/usr/bin/env python3

import rospy
from std_msgs.msg import String


class MPub:
    def __init__(self):
        self.pub = rospy.Publisher('message', String, queue_size=10)
        self.data = String()
        self.i = 0
        rospy.Timer(rospy.Duration(nsecs=330_000_000), self.print_hello)

    def print_hello(self, _event):
        self.data.data = f"hello, ROS! {self.i}"
        rospy.loginfo(self.data.data)
        self.pub.publish(self.data)
        self.i += 1


def main():
    rospy.init_node('mpub')
    node = MPub()
    rospy.spin()


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
