#!/usr/bin/env python3

import rospy
from std_msgs.msg import String


class MSub2:
    def __init__(self):
        self.sub = rospy.Subscriber('message2', String, self.callback)
        self.sub = rospy.Subscriber('message', String, self.callback)
        self.count = 0

    def callback(self, data):
        self.count += 1
        rospy.loginfo(f"{data.data} count: {self.count}")


def main():
    rospy.init_node('msub2')
    node = MSub2()
    rospy.spin()


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
