#!/usr/bin/env python3

import rospy
from std_msgs.msg import Header, String


class MTPub:
    def __init__(self):
        self.pub1 = rospy.Publisher('time', Header, queue_size=10)
        self.pub2 = rospy.Publisher('message2', String, queue_size=10)
        self.msg1 = Header()
        self.msg2 = String()
        self.i = 0
        rospy.Timer(rospy.Duration(nsecs=330_000_000), self.print_hello)

    def print_hello(self, _event):
        self.msg1.stamp = rospy.Time.now()
        self.msg1.frame_id = "base"
        self.msg2.data = f"hello, ROS noetic! {self.i}"
        rospy.loginfo(f"{self.msg1.frame_id} at {self.msg1.stamp.to_sec():.2f}")
        rospy.loginfo(f"{self.msg2.data}")
        self.pub1.publish(self.msg1)
        self.pub2.publish(self.msg2)
        self.i += 1


def main():
    rospy.init_node('mtpub')
    node = MTPub()
    rospy.spin()


if __name__ == "__main__":
    try:
        main()
    except rospy.ROSInterruptException:
        pass
